config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  resources :urls, only: %i[index create show edit update destroy]
  root to: 'urls#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  before_action :set_url, only: %i[show edit update destroy]

  def index
    @urls = Url.all
  end

  def show; end

  def new
    @url = Url.new
  end

  def edit; end

  def create
    url = Url.new(url_params.merge(short_url: build_short_url))
    url.save
    redirect_to url_path(url)
  end

  def update
    @url.update(url_params.merge(short_url: build_short_url))
    redirect_to url_path(@url)
  end

  def destroy
    @url.destroy
    redirect_to root_path
  end

  private

  def set_url
    @url = Url.find(params[:id])
  end

  def url_params
    params.require(:url).permit(:long_url)
  end

  def build_short_url
    rand(1_111_111...9_999_999).to_s
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/urls_helper.rb
# frozen_string_literal: true

module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/edit.html.erb
<h1>Welcome to URL Shortener</h1>
<h2>where you can shorten any long URL</h2>
<p>Here you can update your long URL and we generate a new short URL accordingly.</p>
<%= form_with model: @url do |f| %>
  <%= f.label :long_url %>
  <%= f.text_field :long_url %>
  <%= f.submit %>
<% end %>

app/views/urls/index.html.erb
<h1>Welcome to URL Shortener</h1>
<h2>where you can shorten any long URL</h2>
<p>Here is all the long URLs with their corresponding short URLs</p>
<table>
    <tr>
        <th>Short URL</th>
        <th>Long URL</th>
    </tr>
    <% @urls.each do |url| %>
        <tr>
            <td><%= url.short_url %></td>
            <td><%= url.long_url %></td>
        </tr>
    <% end %>
</table>
<button>
    <%= link_to 'Back to the homepage', root_path %>
</button>

app/views/urls/new.html.erb
<h1>Welcome to URL Shortener</h1>
<h2>where you can shorten any long URL</h2>
<p>Just copy that long URL and paste it down blew in the form and I will make it short and easy to remember</p>
<%= form_with model: @url do |f| %>
  <%= f.label :long_url %>
  <%= f.text_field :long_url %>
  <%= f.submit %>
<% end %>

<p>Do you want to see all of the URLs?</p>
<button><%= link_to 'Yes, show me', urls_path %></button>

app/views/urls/show.html.erb
<h1>Welcome to URL Shortener</h1>
<h2>where you can shorten any long URL</h2>
<p>Here is your Long URL:</p>
<ul>
    <li><%= @url.long_url %></li>
</ul>
<p>Look how short it is now:</p>
<ul>
    <li><%= @url.short_url %></li>
</ul>
<button><%= link_to 'Shorten another', root_path %></button>
<button><%= link_to 'Edit', edit_url_path %></button>
<button><%= link_to 'Delete', url_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></button>